version: '3'

services:
  # app:
  #   build: .
  #   # entrypoint: wait-for db:3306 -t 40 -- ./.docker/entrypoint.sh
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app
  #   depends_on: 
  #     - db
  #   # extra_hosts:
  #   #   - "host.docker.internal:172.17.0.1"

  db:
    build: ./.docker/mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fin
      - MYSQL_ROOT_PASSWORD=root

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    container_name: zookeeper
    ports:
      - "2182:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181 

  kafka:
    image: confluentinc/cp-kafka:5.4.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29094,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper           